In [1]:
import numpy as np


In [2]:
print("NumPy version:", np.__version__)


NumPy version: 1.26.4


In [5]:
a=np.random.random_sample((2, 3, 5))
print("random sample1 ", a)


random sample1  [[[0.89084155 0.25992527 0.08471626 0.20639439 0.37341581]
  [0.90624963 0.73244324 0.74021007 0.05791341 0.38041952]
  [0.61259627 0.80746634 0.7354923  0.23249324 0.4292342 ]]

 [[0.63124601 0.3234701  0.80895147 0.7445844  0.76383097]
  [0.94715236 0.41632143 0.748096   0.63375184 0.94642294]
  [0.06559434 0.20286793 0.97108681 0.97824899 0.28907421]]]


In [6]:
a=np.random.rand(2, 3, 5)
print("random sample2", a)


random sample2 [[[0.04879938 0.8816601  0.52167798 0.43258687 0.58110289]
  [0.51112103 0.51057735 0.63252816 0.09006373 0.95485769]
  [0.25763251 0.24672132 0.2328455  0.35673491 0.12226561]]

 [[0.44277967 0.10389193 0.16665674 0.90423591 0.05722737]
  [0.14037744 0.62741477 0.66579918 0.22797568 0.52202754]
  [0.62631533 0.59917181 0.1817907  0.28893768 0.63997253]]]


In [7]:
a=np.random.uniform(low=0.0, high=1.0, size=(2, 3, 5))
print("random sample3", a)


random sample3 [[[0.11847599 0.30081306 0.32424434 0.25827186 0.21046387]
  [0.63986525 0.30757577 0.40479031 0.41520298 0.54008903]
  [0.2390156  0.91602004 0.2128974  0.65152574 0.50137628]]

 [[0.22384821 0.71960211 0.95866065 0.72328603 0.6793218 ]
  [0.74072741 0.96630958 0.77606002 0.74340292 0.91053835]
  [0.60901639 0.05014538 0.84614956 0.23043387 0.98412074]]]


In [9]:
b=np.ones((5, 2, 3))
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [11]:
if a.size==b.size:
    print("same size")
else:
    print("NOT the same size")


same size


In [12]:
#No,because a and b have diff dimensions

Size of a: 30
Size of b: 30


In [13]:
c=b.transpose((1, 2, 0))  
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [16]:
d=a+c  
#Because both a and c now have the same shape: (2, 3, 5)

In [17]:
print("a",a)
print("d",d)
#Since c has all values of 1, and d = a + c, so each value in d is a + 1.

a [[[0.11847599 0.30081306 0.32424434 0.25827186 0.21046387]
  [0.63986525 0.30757577 0.40479031 0.41520298 0.54008903]
  [0.2390156  0.91602004 0.2128974  0.65152574 0.50137628]]

 [[0.22384821 0.71960211 0.95866065 0.72328603 0.6793218 ]
  [0.74072741 0.96630958 0.77606002 0.74340292 0.91053835]
  [0.60901639 0.05014538 0.84614956 0.23043387 0.98412074]]]
d [[[1.11847599 1.30081306 1.32424434 1.25827186 1.21046387]
  [1.63986525 1.30757577 1.40479031 1.41520298 1.54008903]
  [1.2390156  1.91602004 1.2128974  1.65152574 1.50137628]]

 [[1.22384821 1.71960211 1.95866065 1.72328603 1.6793218 ]
  [1.74072741 1.96630958 1.77606002 1.74340292 1.91053835]
  [1.60901639 1.05014538 1.84614956 1.23043387 1.98412074]]]


In [18]:
e=a*c


In [20]:
print("egal ou pas?:", np.array_equal(e, a))
#e equals a because c is an identity matricx  and a * 1 = a for all elements

egal ou pas?: True


In [21]:
max=d.max()
min=d.min()
mean=d.mean()

print("Max", max)
print("Min", min)
print("Mean", mean)


Max 1.984120737961781
Min 1.0501453794842588
Mean 1.5400750178108393


In [22]:
f=np.empty(d.shape)

In [25]:
for i in range(d.shape[0]):      
    for j in range(d.shape[1]): 
        for k in range(d.shape[2]): 
            value=d[i][j][k]
            if value==min:
                f[i][j][k]=0
            elif value==max:
                f[i][j][k]=100
            elif value == mean:
                f[i][j][k]=50
            elif min<value<mean:
                f[i][j][k]=25
            elif mean<value<max:
                f[i][j][k] = 75


In [26]:
print("d", d)
print("f", f)


d [[[1.11847599 1.30081306 1.32424434 1.25827186 1.21046387]
  [1.63986525 1.30757577 1.40479031 1.41520298 1.54008903]
  [1.2390156  1.91602004 1.2128974  1.65152574 1.50137628]]

 [[1.22384821 1.71960211 1.95866065 1.72328603 1.6793218 ]
  [1.74072741 1.96630958 1.77606002 1.74340292 1.91053835]
  [1.60901639 1.05014538 1.84614956 1.23043387 1.98412074]]]
f [[[ 25.  25.  25.  25.  25.]
  [ 75.  25.  25.  25.  75.]
  [ 25.  75.  25.  75.  25.]]

 [[ 25.  75.  75.  75.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 75.   0.  75.  25. 100.]]]


In [28]:
f2=np.empty(d.shape, dtype=object)
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value=d[i][j][k]
            if value==min:
                f2[i][j][k]='A'
            elif value==max:
                f2[i][j][k]='E'
            elif value==mean:
                f2[i][j][k]='C'
            elif min<value<mean:
                f2[i][j][k]='B'
            elif mean<value<max:
                f2[i][j][k]='D'
print(f2)


[[['B' 'B' 'B' 'B' 'B']
  ['D' 'B' 'B' 'B' 'D']
  ['B' 'D' 'B' 'D' 'B']]

 [['B' 'D' 'D' 'D' 'D']
  ['D' 'D' 'D' 'D' 'D']
  ['D' 'A' 'D' 'B' 'E']]]
